Repository comicrelief/pattern-lab, pull requests merged in 2018-03, with the labels that each got.

#524 feat: donate - cr donate theme main form width
  sass/themes/donate/donate-cr/components/form/_form.scss
Labels: In Progress

#534 fix: donate cr sub theme checkbox styling
  sass/themes/donate/donate-cr/components/form/_form.scss
Labels: Code Reviewed, ready for qa

#540 fix: base - remove logo from press release article
  sass/base/components/news-article/_press-release-article.scss
Labels: In Code Review

#527 feat: donate cr subtheme promo header
  Gruntfile.js
  sass/themes/donate/donate-cr/components/form/_form.scss
  sass/themes/donate/donate-cr/components/promo-header/_promo-header.scss
  sass/themes/donate/donate-cr/components/promo-header/images/promo-header-cr-donate-mob.jpg
  sass/themes/donate/donate-cr/components/promo-header/images/promo-header-cr-donate.jpg
  sass/themes/donate/donate-cr/donate-cr.scss
  sass/themes/payin/components/images/alert-icon.png
  sass/themes/payin/components/images/arrow.png
  sass/themes/payin/components/images/checkbox-checked.png
  sass/themes/payin/components/images/checkbox-tick-new.png
  sass/themes/payin/components/images/checkbox.png
  sass/themes/payin/components/images/form_sprite.png
  sass/themes/payin/components/images/frsb.png
  sass/themes/payin/components/images/icon_sprite.png
  sass/themes/payin/components/images/info-icon.jpg
  sass/themes/payin/components/images/info-icon.png
  sass/themes/payin/components/images/loader.gif
  sass/themes/payin/components/images/lookup-icon.png
  sass/themes/payin/components/images/payment_icon.jpg
Labels: Code Reviewed, In QA

#528 CR Donate - theme header
  sass/themes/donate/donate-cr/components/header/_header.scss
  sass/themes/donate/donate-cr/donate-cr.scss
  sass/themes/donate/sr18/donate-page.twig
Labels: Code Reviewed

#544 donate cr-donate more form styling
  Gruntfile.js
  sass/themes/donate/donate-cr/components/form/_form.scss
  sass/themes/donate/donate-cr/components/promo-header/_promo-header.scss
  sass/themes/donate/donate-cr/donate-cr.scss
  sass/themes/donate/donate-cr/variables/_colours.scss
  sass/themes/payin/default/components/_payin-form.scss
  sass/themes/payin/default/components/images/drop-down-dark-purple.svg
Labels: Passed QA

#550 Center step counter totaliser
  sass/themes/sr/2018/components/live-total-block/_live-total-block.scss
Labels: ready for qa

#554 donate cr theme failure page
  sass/themes/donate/donate-cr/components/promo-header/_promo-header.scss
  sass/themes/donate/sr18/failure-page.twig
Labels: In Code Review

#549 donate - cr-donate subtheme buttons
  sass/themes/donate/donate-cr/components/form/_form.scss
  sass/themes/donate/donate-cr/components/promo-header/_promo-header.scss
  sass/themes/donate/donate-cr/donate-cr.scss
  sass/themes/donate/sr18/_donate-sr18-styles.scss
  sass/themes/donate/sr18/components/form/_form.scss
  sass/themes/donate/sr18/donate-page.twig
  sass/themes/payin/default/components/_payin-form.scss
  sass/themes/payin/default/components/images/paypal.svg
Labels: In Code Review

#541 Donate CR theme success page
  sass/themes/donate/donate-cr/components/cards/_cards.scss
  sass/themes/donate/donate-cr/components/promo-header/_promo-header.scss
  sass/themes/donate/donate-cr/components/success/_success.scss
  sass/themes/donate/donate-cr/donate-cr.scss
  sass/themes/donate/sr18/thank-you-page.twig
  sass/themes/payin/default/components/_payin-form.scss
Labels: In Progress
