Repository comicrelief/pattern-lab, pull requests merged in 2018-02, with the labels that each got.

#493 payin - thank you page
  kss/kss-assets/images/sr18_logo_date_blacktext.svg
  sass/themes/payin/default/variables/_payin-colours.scss
  sass/themes/payin/sportrelief/components/cards/_cards.scss
  sass/themes/payin/sportrelief/components/failure/_failure.scss
  sass/themes/payin/sportrelief/components/promo-header/_promo-header.scss
  sass/themes/payin/sportrelief/components/success/_success.scss
  sass/themes/payin/sportrelief/pages/payin-page.twig
  sass/themes/payin/sportrelief/pages/success-page.twig
  sass/themes/payin/sportrelief/pages/thank-you-page.twig
  sass/themes/payin/sportrelief/payin-sportrelief.scss
Labels: In Progress

#500 fix: payin checkboxes
  sass/themes/payin/default/components/_payin-form.scss
  sass/themes/payin/sportrelief/components/form/_form.scss
  sass/themes/payin/sportrelief/components/success/_success.scss
  sass/themes/payin/sportrelief/pages/payin-page.twig
  sass/themes/payin/sportrelief/pages/success-page.twig
Labels: Code Reviewed

#512 Fix: frost set up team page spacing
  sass/themes/frost/core/components/_form.scss
Labels: In Code Review
